apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers: 
      - name: api
        image: blog-api:1.5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: "DB_HOST"
            value: "database-svc"
          - name: "DB_NAME"
            value: "ahmad_blog_api"
          - name: "DB_USER"
            value: "ahmad"
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-svc
  namespace: blog
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}