apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        ports:
        - containerPort: 3306
        command: ["curl"]
        args: ["https://raw.githubusercontent.com/Ahmad-Faqehi/Locker_System/main/db/lockers_v4.sql", "-o","docker-entrypoint-initdb.d/init.sql"]
        env:
          - name: "MYSQL_DATABASE"
            value: "ahmad_blog_api"
          - name: "MYSQL_USER"
            value: "ahmad"
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: root-password

          - name: "MYSQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password

        initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', 'curl', "https://raw.githubusercontent.com/Ahmad-Faqehi/Locker_System/main/db/lockers_v4.sql -o /tmp/init.sql"]
                  
        volumeMounts:
          - name: somtheingnew
            mountPath: "/var/lib/mysql"

      volumes:
        - name: somtheingnew
          persistentVolumeClaim:
            claimName: db-mysql-pvc


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: U29IYXJkUEBhc3MwcmQ=
  root-password: U29IYXJkUEBhc3MwcmQ=

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database        
  name: database-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: database
