apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers: 
      - name: frontend
        image: ahmad75/blog-vue
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "250Mi"
            cpu: "150m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
          - name: "VUE_APP_BASE_API"
            value: "https://68c55196-a668-4b12-af04-3f03c3e42fb9-10-244-10-56-30090.spch.r.killercoda.com/api"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-svc
  namespace: blog
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30070
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}