apiVersion: v1 
kind: Pod 
metadata:  
    name: two-containers 
spec:  
  volumes:  
    - name: shared-data    
      emptyDir: {}  

  containers:  
  - name: first    
    image: mysql:5.7 
    volumeMounts:    
    - name: shared-data      
      mountPath: /docker-entrypoint-initdb.d
    env:
      - name: "MYSQL_DATABASE"
        value: "ahmad_blog_api"
      - name: "MYSQL_USER"
        value: "ahmad"
      - name: "MYSQL_ROOT_PASSWORD"
        value: "D556@dfsdPP"
      - name: "MYSQL_PASSWORD"
        value: "D556@dfsdPP"
  
  initContainers:
  - name: second    
    image: ahmad75/testt:2.2
    volumeMounts:    
    - name: shared-data      
      mountPath: /pod-data
    #command: ["sh", "-c"," sleep 2; echo WoWoW >> /pod-data/hello.txt"]
    # command: ["sh", "-c"," sleep 2; curl https://raw.githubusercontent.com/Ahmad-Faqehi/Locker_System/main/db/lockers_v4.sql >> /pod-data/init.sql"]
